Repository API-Guild/marvel-basement, pull requests merged in 2021-01, with the labels that each got.

#1 Develop
  README.md
Labels: documentation

#4 Update develop
  index.html
Labels: good first issue

#5 Jmc header and description
  assets/images/marvel-bg.jpg
  assets/script.js
  assets/style.css
  index.html
Labels: enhancement

#13 Develop
  assets/images/marvel-basement-wireframe.png
  assets/images/marvel-bg.jpg
  assets/script.js
  assets/style.css
  index.html
Labels: enhancement

#23 Mock server AJAX + some extra fixes
  assets/images/comic0.jpg
  assets/images/comic1.jpg
  assets/images/favicon.png
  assets/objects/gif-hulk.json
  assets/objects/marvel-hulk.json
  assets/script.js
  assets/style.css
  index.html
Labels: enhancement

#31 Shadow
  assets/style.css
  index.html
Labels: enhancement

#32 Local storage
  assets/script.js
  index.html
Labels: enhancement

#38 Thumbnail update
  assets/script.js
  assets/style.css
  index.html
Labels: enhancement

#39 more semantic html and cleaned up console.logs
  assets/script.js
  index.html
Labels: enhancement

#40 Css clean
  assets/style.css
  index.html
Labels: enhancement

#44 finalized README
  README.md
  assets/images/MB-screenshot.png
Labels: enhancement

#45 Update Main
  README.md
  assets/images/MB-screenshot.png
  assets/images/back2.png
  assets/images/comic0.jpg
  assets/images/comic1.jpg
  assets/images/favicon.png
  assets/objects/gif-hulk.json
  assets/objects/marvel-hulk.json
  assets/script.js
  assets/style.css
  index.html
Labels: enhancement

#46 Update README.md
  README.md
Labels: documentation

#48 Update with fix for favorites bug
  README.md
  assets/script.js
  index.html
Labels: bug

#50 Fixes HTTP loading of thumbnails
  index.html
Labels: bug
